version: '3.7'

services:
  backend:
    build:
     context: ./backend/app
     dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/app/.env.dev
    depends_on:
      - usersnack-db
  # backend-prod:
  #   build:
  #    context: ./backend/app
  #    dockerfile: Dockerfile.prod
  #   volumes:
  #     - ./backend/app/:/usr/src/app/
  #   ports:
  #     - 8001:8765
  #   environment:
  #     - PORT=8765
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #   depends_on:
  #     - usersnack-db      
  usersnack-db:
    image: postgres:12.0-alpine
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432  
    environment:
      - POSTGRES_USER=usersnack
      - POSTGRES_PASSWORD=usersnack
      - POSTGRES_DB=usersnack_dev

volumes:
  postgres_data:   