# Generated by Django 3.0.5 on 2020-05-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='pizza_orders.FoodItem'),
        ),
    ]
